var fs = require("fs");
function main() {
  var results = [];
  var imageId = [
    "4th of July flyer",
    "50th Birthday Invitation",
    "Acting Resume",
    "Advertisement",
    "Advertising",
    "Aesthetic",
    "After School Poster",
    "Agenda",
    "Agriculture",
    "Agriculture Logo",
    "Agriculture Post",
    "Agriculture Poster",
    "Agriculture Presentation",
    "Album Cover",
    "All About Me Worksheet",
    "Animal Flyer",
    "Animal",
    "Animal Poster",
    "Anniversary",
    "Anniversary Invitation",
    "Anniversary Post",
    "Anniversary Story",
    "Announcement",
    "Announcement Poster",
    "Anti-Bullying Poster",
    "Appointment Card",
    "Architecture",
    "Architecture Logo",
    "Architecture Post",
    "Architecture Poster",
    "Architecture Presentation",
    "Army",
    "Art",
    "Art Exhibition Flyer",
    "Art Logo",
    "Arts Poster",
    "Autumn",
    "Autumn Post",
    "Autumn Poster",
    "Autumn Sale Post",
    "Autumn Sale Poster",
    "Autumn Sale Story",
    "Awareness Post",
    "Awareness Poster",
    "Awareness Story",
    "Baby Announcement",
    "Baby Announcement Invitation",
    "Baby Announcement Post",
    "Baby Announcement Story",
    "Baby Shower",
    "Baby Shower Invitation",
    "Baby Shower Post",
    "Baby Shower Story",
    "Baby Shower Thank You Card",
    "Babysitting Flyer",
    "Bachelorette Party Invitation",
    "Back to School",
    "Back to School Post",
    "Back to School Poster",
    "Back to School Presentation",
    "Baker Business Card",
    "Bakery Flyer",
    "Bakery Logo",
    "Bakery Menu",
    "Bakery Poster",
    "Band Flyer",
    "Band Logo",
    "Band Poster",
    "Baptism Announcement",
    "Baptism Invitation",
    "Baptism Place Card",
    "Baptism Thank You Card",
    "Bar Menu",
    "Basketball Logo",
    "Basketball Poster",
    "Basketball Practice Plan",
    "Bathroom Poster",
    "BBQ Menu",
    "Beauty",
    "Beauty Logo",
    "Beauty Post",
    "Beauty Story",
    "Beer Label",
    "Benefit Flyer",
    "Bingo Card",
    "Birth Announcement",
    "Birthday",
    "Birthday Banner",
    "Birthday Card",
    "Birthday Certificate",
    "Birthday Collage",
    "Birthday Invitation",
    "Birthday Post",
    "Birthday Poster",
    "Birthday Story",
    "Black Friday Banner",
    "Black Friday Post",
    "Black Friday Poster",
    "Black Friday Story",
    "Black History Month Poster",
    "Black Lives Matter Poster",
    "Block Party Flyer",
    "BOGO Poster",
    "Book Cover",
    "Book Fair Poster",
    "Book Logo",
    "Book Review",
    "Book Signing Poster",
    "Boot Camp Flyer",
    "Bowling Flyer",
    "Boxing Poster",
    "Breakfast",
    "Breakfast Menu",
    "Breast Cancer Post",
    "Breast Cancer Poster",
    "Bridal Shower Invitation",
    "Brunch Flyer",
    "Business",
    "Business Banner",
    "Business Brochure",
    "Business Card",
    "Business Flyer",
    "Business Logo",
    "Business Plan",
    "Business Post",
    "Business Poster",
    "Business Presentation",
    "Cafe",
    "Cafe Flyer",
    "Cafe Menu",
    "Cafe Post",
    "Cafe Poster",
    "Cafe Story",
    "Cake Logo",
    "Calendar",
    "Camera Logo",
    "Campaign Poster",
    "Camping Post",
    "Camping Poster",
    "Camping Story",
    "Car Banner",
    "Car Logo",
    "Car Show Flyer",
    "Car Wash Poster",
    "Career Fair Poster",
    "Casino Poster",
    "Cat Logo",
    "Catering Business Cards",
    "Catering Flyer",
    "Catering Menu",
    "Catering Post",
    "CD Cover",
    "Celebration of Life Invitation",
    "Certificate",
    "Certificate of Achievement",
    "Certificate of Appreciation",
    "Certificate of Attendance",
    "Certificate of Award",
    "Certificate of Completion",
    "Certificate of Diploma",
    "Certificate of Internship",
    "Certificate of Membership",
    "Certificate of Participation",
    "Certificate of Recognition",
    "Children's Book Cover",
    "Chinese",
    "Chinese New Year",
    "Chinese New Year Card",
    "Chinese New Year Social Media",
    "Chinese New Year Story",
    "Christmas",
    "Christmas Banner",
    "Christmas Card",
    "Christmas Facebook Cover",
    "Christmas Invitation",
    "Christmas Party Poster",
    "Christmas Post",
    "Christmas Postcard",
    "Christmas Story",
    "Church Flyer",
    "Circus Poster",
    "Clan Logo",
    "Class",
    "Class Schedule",
    "Classroom Poster",
    "Cleaning Service Poster",
    "Climate Change Poster",
    "Clothing",
    "Clothing Logo",
    "Club Flyer",
    "Coffee Logo",
    "Coffee Menu",
    "Collage",
    "Comedy Show Poster",
    "Coming Soon Poster",
    "Company",
    "Company Brochure",
    "Company Business Card",
    "Company Flyer",
    "Company Logo",
    "Company Presentation",
    "Concert Flyer",
    "Concert Post",
    "Concert Poster",
    "Concert Story",
    "Concert Ticket",
    "Conference Flyer",
    "Confirmation Announcement",
    "Confirmation Invitation",
    "Congratulations Card",
    "Construction",
    "Construction Flyer",
    "Construction Logo",
    "Cookbook Cover",
    "Corporate",
    "Corporate Brochure",
    "Corporate Business Card",
    "Corporate Flyer",
    "Corporate Poster",
    "Course",
    "Course Post",
    "Course Poster",
    "Cover Letter",
    "Covid 19",
    "Covid 19 Post",
    "Covid 19 Poster",
    "Creative Resume",
    "Crown Logo",
    "Cyber Monday Advertisement",
    "Cyber Monday Post",
    "Cyber Monday Poster",
    "Cyber Monday Story",
    "Daily Planner",
    "Dance Poster",
    "Daycare Flyer",
    "Daycare Post",
    "Death Announcement",
    "Death Announcement Invitation",
    "Dental Logo",
    "Dentist Brochure",
    "Dentist Business Card",
    "Dentist Flyer",
    "Dentist Post",
    "Dentist Poster",
    "Digital Invitation",
    "Digital Marketing Banner",
    "Dinner Menu",
    "Diwali Banner",
    "DJ Business Card",
    "DJ Logo",
    "DJ Poster",
    "Doctor",
    "Doctor Business Card",
    "Doctor Post",
    "Doctor Resume",
    "Dog Adoption Poster",
    "Dog Flyer",
    "Dog Logo",
    "Dog Post",
    "Dog Poster",
    "Dog Walker Flyer",
    "Donations Flyer",
    "Donations Poster",
    "Drink",
    "Drink Menu",
    "Eagle Logo",
    "Earth Day",
    "Earth Day Banner",
    "Earth Day Post",
    "Earth Day Poster",
    "Earth Day Story",
    "Easter",
    "Easter Banner",
    "Easter Post",
    "Easter Poster",
    "Easter Story",
    "Eco",
    "Eco Banner",
    "Eco Logo",
    "Eco Post",
    "Education",
    "Education Flyer",
    "Education Logo",
    "Education Post",
    "Education Poster",
    "Eid Mubarak Card",
    "Eid Mubarak Post",
    "Eid Mubarak Story",
    "Election Post",
    "Election Poster",
    "Electrical Logo",
    "Energy Logo",
    "Engagement",
    "Engagement Announcement",
    "Engagement Invitation",
    "Environment",
    "Environment Banner",
    "Environment Post",
    "Environment Poster",
    "Environment Presentation",
    "Environment Story",
    "Esports Logo",
    "Event",
    "Event Banner",
    "Event Calendar",
    "Event Flyer",
    "Event Poster",
    "Event Program",
    "Exhibition Flyer",
    "Exhibition Post",
    "Exhibition Poster",
    "Family",
    "Farm Logo",
    "Farm Post",
    "Fashion",
    "Fashion Banner",
    "Fashion Collage",
    "Fashion Logo",
    "Fashion Magazine Cover",
    "Fashion Post",
    "Fashion Poster",
    "Fashion Show Flyer",
    "Fashion Story",
    "Father’s Day Card",
    "Father’s Day Post",
    "Father’s Day Story",
    "Festival",
    "Festival Banner",
    "Festival Post",
    "Festival Poster",
    "Festival Story",
    "Film Festival Post",
    "Film Festival Poster",
    "Finance",
    "Finance Logo",
    "Finance Post",
    "Finance Presentation",
    "Fire Logo",
    "First Birthday Invitation",
    "First Communion Announcement",
    "First Day of School Sign",
    "Fitness",
    "Fitness Banner",
    "Fitness Flyer",
    "Fitness Logo",
    "Fitness Post",
    "Fitness Poster",
    "Floral",
    "Floral Business Card",
    "Floral Invitation",
    "Floral Logo",
    "Florist Business Card",
    "Florist Resume",
    "Flower Post",
    "Flower Shop Business Card",
    "Flower Shop Logo",
    "Flower Shop Post",
    "Flower Shop Story",
    "Flower Story",
    "Food",
    "Food And Drink Menu",
    "Food Banner",
    "Food Brochure",
    "Food Flyer",
    "Food Flyer",
    "Food Logo",
    "Food Post",
    "Food Poster",
    "Food Story",
    "Football Logo",
    "For Rent Flyer",
    "Fundraiser Flyer",
    "Funeral Announcement",
    "Funeral Card",
    "Funeral Program",
    "Funeral Thank You Card",
    "Furniture Logo",
    "Furniture Post",
    "Furniture Sale Flyer",
    "Furniture Sale Post",
    "Furniture Sale Poster",
    "Furniture Sale Story",
    "Furniture Story",
    "Gala Poster",
    "Game Logo",
    "Game Night Flyer",
    "Gender Reveal Flyer",
    "Get Well Soon Card",
    "Gift Certificate",
    "Goal-Setting Worksheet",
    "Golf Tournament Flyer",
    "Good Luck Card",
    "Graduation Album Cover",
    "Graduation Announcement",
    "Graduation Banner",
    "Graduation Card",
    "Graduation Congratulations Card",
    "Graduation Invitation",
    "Graduation Post",
    "Graduation Poster",
    "Graduation Program",
    "Graduation Story",
    "Grand Opening Flyer",
    "Grand Opening Post",
    "Graphic Design Resume",
    "Graphic Designer Business Card",
    "Greeting",
    "Grocery List",
    "Gym Business Card",
    "Gym Flyer",
    "Gym Post",
    "Gym Poster",
    "Halloween Flyer",
    "Halloween Party Invitation",
    "Halloween Party Menu",
    "Halloween Party Thank you Card",
    "Hanukkah Card",
    "Happy Diwali Greeting Card",
    "Happy Easter Card",
    "Happy Hour Flyer",
    "Happy Hour Invitation",
    "Happy Hour Post",
    "Happy Hour Poster",
    "Hawaiian Birthday Invitation",
    "Health",
    "Health Banner",
    "Health Post",
    "Health Poster",
    "Health Presentation",
    "Healthcare",
    "Healthcare Banner",
    "Healthcare Post",
    "Healthcare Poster",
    "Healthcare Presentation",
    "Heart Logo",
    "Help Wanted Poster",
    "High School Resume",
    "Highlight Covers",
    "Hip Hop Poster",
    "Holiday",
    "Holiday Card",
    "Holiday Party Flyer",
    "Holiday Party Post",
    "Holiday Party Poster",
    "Hospital",
    "Hospital Logo",
    "Hospital Post",
    "Hospital Poster",
    "Hotel Brochure",
    "Hotel Logo",
    "Hotel Post",
    "Hotel Story",
    "House For Sale Flyer",
    "House For Sale Post",
    "Housewarming Invitation",
    "Ice Cream Poster",
    "In Loving Memory Card",
    "Industry",
    "Industry Logo",
    "Industry Post",
    "Industry Poster",
    "Industry Presentation",
    "Inspirational",
    "Interior",
    "Interior Design Business Card",
    "Interior Design Flyer",
    "Interior Logo",
    "Invitation",
    "Invoice",
    "Itinerary",
    "Jazz Night Flyer",
    "Jewelry Poster",
    "Job Poster",
    "Jobs",
    "Journal",
    "Karaoke Flyer",
    "Keep Calm Poster",
    "Kids",
    "Kids Birthday Card",
    "Kids Menu",
    "Labor Day Poster",
    "Ladies Night Out Flyer",
    "Lawn Care Business Flyer",
    "Lawyer Business Card",
    "Lesson Plan",
    "LGBTQ",
    "LGBTQ Post",
    "LGBTQ Story",
    "LGBTQ Wedding Invitation",
    "Lingerie Shower Invitation",
    "LinkedIn Banner",
    "Lion Logo",
    "Live Music Flyer",
    "Love",
    "Magazine Cover",
    "Makeup",
    "Makeup Business Card",
    "Makeup Post",
    "Makeup Story",
    "Marketing",
    "Marketing Banner",
    "Marketing Logo",
    "Marketing Plan",
    "Marketing Post",
    "Marketing Poster",
    "Marketing Presentation",
    "Marketing Resume",
    "Masquerade Invitation",
    "Massage Flyer",
    "Massage Gift Certificate",
    "Meal Planner",
    "Medical",
    "Medical Banner",
    "Medical Brochure",
    "Medical Certificate",
    "Medical Logo",
    "Medical Post",
    "Medical Poster",
    "Medicine",
    "Meeting Agenda",
    "Meeting Minute",
    "Memo",
    "Memorial Day Flyer",
    "Memphis",
    "Mental health",
    "Mental health Banner",
    "Mental health Logo",
    "Mental health Post",
    "Mental health Poster",
    "Menu",
    "Minimal Logo",
    "Minimalist Book Cover",
    "Missing Cat Poster",
    "Missing Dog Poster",
    "Missing Pet Poster",
    "Missing Poster",
    "Mixtape Cover",
    "Mobile Logo",
    "Modern Logo",
    "Modern Resume",
    "Mood Board",
    "Mother's Day",
    "Mother's Day Post",
    "Mother’s Day Card",
    "Motivational",
    "Motivational Post",
    "Motivational Poster",
    "Motivational Story",
    "Mountain Logo",
    "Movie Logo",
    "Movie Night Post",
    "Movie Night Poster",
    "Movie Poster",
    "Museum Poster",
    "Music",
    "Music Banner",
    "Music Collage",
    "Music Festival Post",
    "Music Festival Poster",
    "Music Festival Poster",
    "Music Festival Story",
    "Music Lessons Flyer",
    "Music Logo",
    "Music Post",
    "Music Poster",
    "Music Story",
    "Nature",
    "Nature Banner",
    "Nature Logo",
    "Nature Post",
    "Nature Poster",
    "Neon",
    "Neon Logo",
    "Neon Sign",
    "Networking Card",
    "New puppy announcement",
    "New Year",
    "New Year Banner",
    "New Year Post",
    "New Year Poster",
    "New Year Sale Banner",
    "New Year Sale Post",
    "New Year Sale Poster",
    "New Year Sale Story",
    "New Year Story",
    "New Year’s Card",
    "Newsletter",
    "Newspaper",
    "Nightclub Flyer",
    "Note Card",
    "Notebook Cover",
    "Now Hiring Poster",
    "Oktoberfest Invitation",
    "Open House Flyer",
    "Opening Soon Poster",
    "Parent",
    "Party",
    "Party Banner",
    "Party Flyer",
    "Party Invitation",
    "Party Post",
    "Party Poster",
    "Party Story",
    "People",
    "Personal Planner",
    "Personal Trainer Flyer",
    "Pet Shop Business Card",
    "Pet Shop Post",
    "Pet Shop Poster",
    "Pharmacy Logo",
    "Phone Logo",
    "Photography",
    "Photography Flyer",
    "Photography Logo",
    "Picnic Flyer",
    "Planner",
    "Plant Care Card",
    "Political Poster",
    "Pool Party",
    "Pool Party Banner",
    "Pool Party Flyer",
    "Pool Party Invitation",
    "Pool Party Post",
    "Pool Party Poster",
    "Pool Party Story",
    "Potluck Invitation",
    "Pregnancy Announcement",
    "Preschool Flyer",
    "Preschool Worksheet",
    "Price List",
    "Princess Invitation",
    "Product",
    "Product Brochure",
    "Product Flyer",
    "Professional Resume",
    "Prom Poster",
    "Property Brochure",
    "Property Flyer",
    "Quiz",
    "Quiz Night Poster",
    "Quotation",
    "Quote",
    "Quote Post",
    "Quote Poster",
    "Quote Story",
    "Rack Card",
    "Raffle Ticket",
    "Ramadan",
    "Ramadan Banner",
    "Ramadan Post",
    "Ramadan Poster",
    "Ramadan Story",
    "Real Estate",
    "Real Estate Banner",
    "Real Estate Brochure",
    "Real Estate Business Card",
    "Real Estate Flyer",
    "Real Estate Logo",
    "Real Estate Post",
    "Real Estate Poster",
    "Real Estate Presentation",
    "Recipe",
    "Recommendation Letter",
    "Recruitment",
    "Recruitment Post",
    "Recruitment Poster",
    "Recruitment Story",
    "Rehearsal Invitation",
    "Report",
    "Research Poster",
    "Rest in Peace Card",
    "Restaurant",
    "Restaurant Banner",
    "Restaurant Business Card",
    "Restaurant Flyer",
    "Restaurant Logo",
    "Restaurant Post",
    "Restaurant Poster",
    "Restaurant Story",
    "Resume",
    "Retail",
    "Retirement Party Invitation",
    "Retro",
    "Romance",
    "RSVP Card",
    "Rustic Wedding Invitation",
    "Saint Patrick's Day Flyer",
    "Saint Patrick's Day Post",
    "Salary Certificate",
    "Sale",
    "Sale Banner",
    "Sale Brochure",
    "Sale Flyer",
    "Sale Post",
    "Sale Poster",
    "Sale Story",
    "Salon Business Card",
    "Salon Flyer",
    "Salon Logo",
    "Salon Post",
    "Salon Poster",
    "Save The Date",
    "Save the Date Invitation",
    "Save The Date Post",
    "Save The Date Poster",
    "Save The Date Story",
    "School",
    "School Announcement",
    "School Banner",
    "School Brochure",
    "School Dance Poster",
    "School Logo",
    "School Poster",
    "Seminar Poster",
    "Service",
    "Shield Logo",
    "Shop Banner",
    "Shop Brochure",
    "Shop Business Card",
    "Shop Flyer",
    "Shop Logo",
    "Shop Poster",
    "Signage",
    "Sleepover Invitation",
    "Soccer Logo",
    "Soccer Poster",
    "Social Distance Poster",
    "Social Issue",
    "Social media",
    "Social Media Banner",
    "Social Media Graphic",
    "Social Media Logo",
    "Social Media Post",
    "Social Media Story",
    "Spa",
    "Spa Brochure",
    "Spa Flyer",
    "Spiritual",
    "Sport",
    "Sport Post",
    "Sport Poster",
    "Sports Banner",
    "Sports Flyer",
    "Sports Logo",
    "Spring",
    "Stand with Ukraine",
    "Sticker Logo",
    "Store",
    "Student Business Card",
    "Student Council Poster",
    "Summer",
    "Summer Camp Poster",
    "Super Bowl Poster",
    "Superhero Invitation",
    "Sweet 16 Invitation",
    "Sympathy Card",
    "Sympathy Post",
    "Sympathy Story",
    "Talent Show Flyer",
    "Tattoo Poster",
    "Tax Flyer",
    "Tea Party Invitation",
    "Tea Party Poster",
    "Teacher’s Day Card",
    "Technology",
    "Technology Banner",
    "Technology Business Card",
    "Technology Logo",
    "Technology Presentation",
    "Thank You",
    "Thank You Card",
    "Thank You Poster",
    "Thanksgiving",
    "Thanksgiving Card",
    "Thanksgiving Menu",
    "Thanksgiving Poster",
    "To Do List",
    "Toy Drive Flyer",
    "Travel",
    "Travel Banner",
    "Travel Brochure",
    "Travel Flyer",
    "Travel Logo",
    "Travel Post",
    "Travel Postcard",
    "Travel Story",
    "Tree Logo",
    "Tumblr Banner",
    "Tumblr Collage",
    "Tutorial Flyer",
    "Twitch Banner",
    "Twitch Logo",
    "Twitch Overlay",
    "Twitter Banner",
    "Twitter Header",
    "Typography Logo",
    "Typography Poster",
    "Unicorn Birthday Card",
    "Unicorn Invitation",
    "Valentine's Day",
    "Valentine's Day Banner",
    "Valentine's Day Post",
    "Valentine's Day Story",
    "Valentine’s Day Card",
    "Vintage",
    "Vintage Banner",
    "Vintage Brochure",
    "Vintage Business Card",
    "Vintage Flyer",
    "Vintage Invitation",
    "Vintage Logo",
    "Vintage Post",
    "Vintage Poster",
    "Vintage Resume",
    "Vintage Story",
    "Vinyl Banner",
    "Virtual Business Card",
    "Volleyball Logo",
    "Volunteer Poster",
    "Wanted Poster",
    "Wash Your Hands Poster",
    "Watercolor",
    "Watercolor Banner",
    "Watercolor Brochure",
    "Watercolor Business Card",
    "Watercolor Flyer",
    "Watercolor Invitation",
    "Watercolor Logo",
    "Watercolor Post",
    "Watercolor Poster",
    "Watercolor Presentation",
    "Watercolor Resume",
    "Watercolor Story",
    "We Are Open Poster",
    "Website Announcement",
    "Website Banner",
    "Website Logo",
    "Wedding",
    "Wedding Announcement",
    "Wedding Banner",
    "Wedding Brochure",
    "Wedding Invitation",
    "Wedding Logo",
    "Wedding Menu",
    "Wedding Photo Album",
    "Wedding Program",
    "Wedding Seating Chart",
    "Wedding Thank You Card",
    "Wedding Video Intro",
    "Weekly Calendar",
    "Weekly Menu",
    "Weekly Schedule",
    "Welcome",
    "Welcome Banner",
    "Welcome Post",
    "Welcome Poster",
    "Welcome Story",
    "Wellness",
    "Wellness Banner",
    "Wellness Post",
    "Wellness Poster",
    "Wellness Presentation",
    "Will You Be My Bridesmaid Card",
    "Wine Tasting Flyer",
    "Winner Announcement",
    "Winter",
    "Winter Post",
    "Winter Story",
    "Woman",
    "Work Experience Certificate",
    "Workout",
    "Workout Calendar",
    "Workout plan",
    "Worksheet",
    "Workshop",
    "Workshop Flyer",
    "Workshop Poster",
    "Yard Sale",
    "Yard Sale Poster",
    "Yoga Post",
    "Yoga Poster",
  ];

  for (var i = 0; i < imageId.length; i++) {
    var urlLink = imageId[i].replaceAll(" ", "%20").toLowerCase();
    var result = `https://create.vista.com/api/v2/search/templates?limit=50&skip=0&templateType=regular%2Canimated&searchByKeyword=false&section=templatesPage&q=${urlLink}&_ga=GA1.1.1850159779.1658132136`;
    results.push(result);
  }
  //console.log(uniqueitem);
  var json = JSON.stringify(results);

  fs.writeFile("template-01.json", json, function (err) {
    if (err) {
      return console.log(err);
    }

    console.log("The file was saved!");
  });
}
main();
